### ISSUE TITLE
图表尺寸过小导致部分内容显示不出来

### ISSUE THREAD

**Issue by Deep-Dark-Forest** [PCL-Community/PCL2-Github-Info-Dashboard#12]
![image](https://github.com/PCL-Community/PCL2-Github-Info-Dashboard/assets/131975043/67c3c745-01cb-4e10-b481-f08c5fb3c6b9)
处理中，投票中，推迟，需要社区帮助被生吃了

**Comment by JingHai-Lingyun** [comment]
。。。

**Comment by JingHai-Lingyun** [comment]
怎么回事

**Comment by JingHai-Lingyun** [comment]
我怎么感觉是 #11 你给修坏了

**Comment by Deep-Dark-Forest** [comment]
？#11我啥也没动啊，就发个issue然后关了

**Comment by Deep-Dark-Forest** [comment]
zkitefly那传来的图片表示没有问题……是我电脑屏幕的问题，不过建议加个屏幕分辨率自适应

**Comment by JingHai-Lingyun** [comment]
忘了说了 这东西在v102版本fix了

**Comment by JingHai-Lingyun** [comment]
现在会根据屏幕大小自动匹配大小
